name: terraform-test

on:
  push:
    branches:
     - "main"

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    steps:
    # Go環境のセットアップ
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
       terraform_version: 0.14.9
    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate -no-color

    - name: check val
      run: ${{github.event_name}}

    - name: Terraform Plan
      if: github.event_name == 'pull_request'
      run: terraform plan -no-color

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event.name == 'push'
      run: terraform apply -auto-approve
# test